/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoodschappenRouteImport } from './routes/boodschappen'
import { Route as FotosRouteImport } from './routes/fotos'
import { Route as GezinRouteImport } from './routes/gezin'
import { Route as KlusjesRouteImport } from './routes/klusjes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as WeekmenuRouteImport } from './routes/weekmenu'
import { Route as ReceptenIndexRouteImport } from './routes/recepten/index'
import { Route as ReceptenReceptIdRouteImport } from './routes/recepten/$receptId'
import { Route as ReceptenNieuwRouteImport } from './routes/recepten/nieuw'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoodschappenRoute = BoodschappenRouteImport.update({
  id: '/boodschappen',
  path: '/boodschappen',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosRoute = FotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const GezinRoute = GezinRouteImport.update({
  id: '/gezin',
  path: '/gezin',
  getParentRoute: () => rootRouteImport,
} as any)
const KlusjesRoute = KlusjesRouteImport.update({
  id: '/klusjes',
  path: '/klusjes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WeekmenuRoute = WeekmenuRouteImport.update({
  id: '/weekmenu',
  path: '/weekmenu',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptenIndexRoute = ReceptenIndexRouteImport.update({
  id: '/recepten/',
  path: '/recepten/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptenReceptIdRoute = ReceptenReceptIdRouteImport.update({
  id: '/recepten/$receptId',
  path: '/recepten/$receptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptenNieuwRoute = ReceptenNieuwRouteImport.update({
  id: '/recepten/nieuw',
  path: '/recepten/nieuw',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/boodschappen': typeof BoodschappenRoute
  '/fotos': typeof FotosRoute
  '/gezin': typeof GezinRoute
  '/klusjes': typeof KlusjesRoute
  '/onboarding': typeof OnboardingRoute
  '/weekmenu': typeof WeekmenuRoute
  '/recepten/$receptId': typeof ReceptenReceptIdRoute
  '/recepten/nieuw': typeof ReceptenNieuwRoute
  '/recepten/': typeof ReceptenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/boodschappen': typeof BoodschappenRoute
  '/fotos': typeof FotosRoute
  '/gezin': typeof GezinRoute
  '/klusjes': typeof KlusjesRoute
  '/onboarding': typeof OnboardingRoute
  '/weekmenu': typeof WeekmenuRoute
  '/recepten/$receptId': typeof ReceptenReceptIdRoute
  '/recepten/nieuw': typeof ReceptenNieuwRoute
  '/recepten': typeof ReceptenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/auth': typeof AuthRoute
  '/boodschappen': typeof BoodschappenRoute
  '/fotos': typeof FotosRoute
  '/gezin': typeof GezinRoute
  '/klusjes': typeof KlusjesRoute
  '/onboarding': typeof OnboardingRoute
  '/weekmenu': typeof WeekmenuRoute
  '/recepten/$receptId': typeof ReceptenReceptIdRoute
  '/recepten/nieuw': typeof ReceptenNieuwRoute
  '/recepten/': typeof ReceptenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/auth'
    | '/boodschappen'
    | '/fotos'
    | '/gezin'
    | '/klusjes'
    | '/onboarding'
    | '/weekmenu'
    | '/recepten/$receptId'
    | '/recepten/nieuw'
    | '/recepten/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/auth'
    | '/boodschappen'
    | '/fotos'
    | '/gezin'
    | '/klusjes'
    | '/onboarding'
    | '/weekmenu'
    | '/recepten/$receptId'
    | '/recepten/nieuw'
    | '/recepten'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/auth'
    | '/boodschappen'
    | '/fotos'
    | '/gezin'
    | '/klusjes'
    | '/onboarding'
    | '/weekmenu'
    | '/recepten/$receptId'
    | '/recepten/nieuw'
    | '/recepten/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AuthRoute: typeof AuthRoute
  BoodschappenRoute: typeof BoodschappenRoute
  FotosRoute: typeof FotosRoute
  GezinRoute: typeof GezinRoute
  KlusjesRoute: typeof KlusjesRoute
  OnboardingRoute: typeof OnboardingRoute
  WeekmenuRoute: typeof WeekmenuRoute
  ReceptenReceptIdRoute: typeof ReceptenReceptIdRoute
  ReceptenNieuwRoute: typeof ReceptenNieuwRoute
  ReceptenIndexRoute: typeof ReceptenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boodschappen': {
      id: '/boodschappen'
      path: '/boodschappen'
      fullPath: '/boodschappen'
      preLoaderRoute: typeof BoodschappenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos': {
      id: '/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof FotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gezin': {
      id: '/gezin'
      path: '/gezin'
      fullPath: '/gezin'
      preLoaderRoute: typeof GezinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klusjes': {
      id: '/klusjes'
      path: '/klusjes'
      fullPath: '/klusjes'
      preLoaderRoute: typeof KlusjesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekmenu': {
      id: '/weekmenu'
      path: '/weekmenu'
      fullPath: '/weekmenu'
      preLoaderRoute: typeof WeekmenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepten/': {
      id: '/recepten/'
      path: '/recepten'
      fullPath: '/recepten/'
      preLoaderRoute: typeof ReceptenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepten/$receptId': {
      id: '/recepten/$receptId'
      path: '/recepten/$receptId'
      fullPath: '/recepten/$receptId'
      preLoaderRoute: typeof ReceptenReceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recepten/nieuw': {
      id: '/recepten/nieuw'
      path: '/recepten/nieuw'
      fullPath: '/recepten/nieuw'
      preLoaderRoute: typeof ReceptenNieuwRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AuthRoute: AuthRoute,
  BoodschappenRoute: BoodschappenRoute,
  FotosRoute: FotosRoute,
  GezinRoute: GezinRoute,
  KlusjesRoute: KlusjesRoute,
  OnboardingRoute: OnboardingRoute,
  WeekmenuRoute: WeekmenuRoute,
  ReceptenReceptIdRoute: ReceptenReceptIdRoute,
  ReceptenNieuwRoute: ReceptenNieuwRoute,
  ReceptenIndexRoute: ReceptenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
