-- =============================================================
-- Klusjes-uitbreiding, Fase D: push-abonnementen voor Android/Chrome.
--
-- Deze migratie is nooit op de live database toegepast (git-migraties
-- komen hier niet automatisch door). Lovable heeft `push_abonnementen`
-- zelf aangemaakt in migratie 20260831222000_..., dus dit bestand is
-- nu een no-op — bewust leeg gelaten in plaats van verwijderd, zodat
-- `create table public.push_abonnementen` niet twee keer in de
-- migratiegeschiedenis staat (dat breekt een volledige db reset).
-- =============================================================
